# Generated by Django 3.0.5 on 2021-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Subtitle', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
